# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Vertical farm - IB3
email: klaas.meersman@student.kuleuven.be, axel.martens@student.kuleuven.be, arthur.valentin@student.kuleuven.be, bert.pyck@student.kuleuven.be, ybe.vandamme@student.kuleuven.be, joeri.sevens@student.kuleuven.be, florian.vandenbogaerde@student.kuleuven.be
description: >- # this means to ignore newlines until "baseurl:"
  A description of the vertical farm in Building B, second floor, on the KU Leuven campus in Ghent. This website is used to document the project.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://verticalfarmib3.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: /
github_username:  verticalfarmib3

# Build settings
markdown: kramdown
remote_theme: pages-themes/tactile
plugins:
  - jekyll-feed
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme

kramdown:
  syntax_highlighter: coderay

header_pages:
  - inhoud/leds/index.md
  - inhoud/aansturingLEDs/index.md
  - inhoud/energiemonitoring/index.md
  - inhoud/aquaMonitoring/index.md
  - inhoud/dashboard/index.md
  - inhoud/modulariteit/index.md
  - inhoud/plantensensor/index.md
  - inhoud/operation/index.md
  - inhoud/logboek/index.md
  
google_site_verification: "cBYpSqc17Jx3NXWnR6gz8v8d7Gs7lRmBOXAHTUqdOyM"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
