esphome:
  name: soil-moisture
  friendly_name: Plant sensors

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "twkGFV1QElXeeA3FsTmkHDS0oDe01dTZTraBr5cgp0o="

ota:
  password: "2d1b865c428be14f44812e0af4944fc4"

wifi:
  ssid: CM3
  password: WelcomeToCM3

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Soil-Moisture Fallback Hotspot"
    password: "WUpZNVD42kWQ"

i2c:
  - id: bus_a
    sda: 21
    scl: 22
    scan: true

  - id: bus_b
    sda: 13
    scl: 16
    scan: true

captive_portal:

sensor:
  - platform: scd4x
    i2c_id: bus_a
    co2:
      name: "CO2 1"
    temperature:
      name: "Temperature 1"
    humidity:
      name: "Humidity 1"
    update_interval: 30s

  - platform: scd4x
    i2c_id: bus_b
    co2:
      name: "CO2 2"
    temperature:
      name: "Temperature 2"
    humidity:
      name: "Humidity 2"
    update_interval: 30s


  - platform: adc
    pin: GPIO34
    id: "adcMoisture1"
    accuracy_decimals: 3
    unit_of_measurement: '%'
    filters:
      - calibrate_linear:
        - 0.920  -> 100.0
        - 1.570 -> 0
    name: "Soil Moister 1"
    update_interval: 30s
    force_update: true

# * - platform: adc
#    pin: GPIO34
#    id: "adcRaw_Sensor_Data1"
#    accuracy_decimals: 5
#     name: "Plant - Sensor Voltage 1"
#    update_interval: 60s

  - platform: adc
    pin: GPIO35
    id: "adcMoisture"
    accuracy_decimals: 3
    unit_of_measurement: '%'
    filters:
      - calibrate_linear:
        - 0.920  -> 100.0
        - 1.570 -> 0
    name: "Soil Moister 2"
    update_interval: 30s
    force_update: true

#  - platform: adc
#    pin: GPIO35
#    id: "adcRaw_Sensor_Data"
#    accuracy_decimals: 5
#    name: "Sensor Voltage 2"
#    update_interval: 60s
